baseURL = 'https://leikercg.github.io'
languageCode = 'es'
title = 'Mi blog personal'
theme=  'tale'

[params]
css=["css/estilos.css"]

[Author]
name="Leiker Castilo"


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0